version: 2.1
jobs:
  build:
    working_directory: /home/circleci/app
    docker:
    - image: circleci/node:10
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Install Node and modules
        command: |
          sudo apt-get update
          curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
          sudo npm install -g @mapbox/cfn-config @mapbox/cloudfriend
    - run:
        name: Set folder permissions
        command: |
          chown -R circleci:circleci $CIRCLE_WORKING_DIRECTORY
          chmod -R 755 $CIRCLE_WORKING_DIRECTORY
    - restore_cache:
        keys:
        - cached-dependencies
        paths:
        - client/node_modules
        - env
    - run:
        name: Install requirements
        command: |
          # Install NPM packages and build client from gulpfile
          cd $CIRCLE_WORKING_DIRECTORY/
          npm install
  deploy:
    parameters:
      stack_name:
        description: "the name of the stack for cfn-config"
        type: string
    working_directory: /home/circleci/stats-collector
    docker:
    - image: circleci/node:10.0
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Set Environment Variables
        command: |
          echo "export JSON_CONFIG='{\"GitSha\":\"$CIRCLE_SHA1\"}'" >> $BASH_ENV
    - run:
        name: Install Node and modules
        command: |
          sudo apt-get update
          curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
          sudo npm install -g @mapbox/cfn-config @mapbox/cloudfriend
          npm install
    - run:
        name: Configure AWS Access Key ID
        command: |
          aws configure set aws_access_key_id \
          $AWS_ACCESS_KEY_ID \
          --profile default
    - run:
        name: Configure AWS Secret Access Key
        command: |
          aws configure set aws_secret_access_key \
          $AWS_SECRET_ACCESS_KEY \
          --profile default
    - run:
        name: Configure AWS default region
        command: |
          aws configure set region $AWS_REGION \
          --profile default
    - run:
        name: Create config file
        command: |
          touch $CIRCLE_WORKING_DIRECTORY/cfn-config-<< parameters.stack_name >>.json
          echo $JSON_CONFIG > $CIRCLE_WORKING_DIRECTORY/cfn-config-<< parameters.stack_name >>.json
    - deploy:
        name: Deploy to << parameters.stack_name >>
        command: cfn-config update << parameters.stack_name >> $CIRCLE_WORKING_DIRECTORY/devops/cloudformation/stats-collector.template.js -f -c hot-cfn-config -t hot-cfn-config -r $AWS_REGION -p "$JSON_CONFIG"
workflows:
  version: 2
  build-deploy:
    jobs:
    - build
    - deploy:
        name: production
        filters:
          branches:
            only:
            - master
        requires:
        - build
        stack_name: "production"
